# Generated by Django 4.0.4 on 2022-05-18 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_username', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_password', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('enquiry_title', models.CharField(blank=True, max_length=255, null=True)),
                ('enquiry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('enquiry_date', models.DateTimeField(auto_now=True)),
                ('enquiry_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('transaction_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_descrption', models.TextField()),
                ('transaction_history', models.TextField()),
                ('transaction_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('payment_bill', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_description', models.TextField()),
                ('payment_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('cargo_sales', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_order', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_description', models.TextField()),
                ('cargo_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargotypes')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('bill_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_description', models.TextField()),
                ('bill_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
